version: 0.2

phases:
  install:
    commands:
      - echo Installing node 16.10
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli@12.0
  test:
    commands:
      - echo Running unit tests...
      - ng test
  build:
    commands:
      - echo Build started on `date`
      - ng build
  post_build:
    commands:
      - echo Build completed on `date`
# reports:
# TODO: Agregarr reportes de pruebas unitarias
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes