apiVersion: v1
kind: Service
metadata:
  name: rbui
  labels:
    app: rbui
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  # type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: NodePort
  ports:
  - port: 8082
    targetPort: 80
    name: http
  selector:
    app: rbui
